version: '3.5'
services:
  grafana:
    image: grafana/grafana-oss:latest
    container_name: grafana
    environment:
      - TZ=Europe/London
    ports:
      - '3000:3000'
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: 'always'
    volumes:
      - /data/noshare/grafana:/var/lib/grafana
