#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---

- name: Create directory for docker-compose.yml
  ansible.builtin.file:
    path: "/home/{{ create_user }}/compose"
    state: directory
    owner: "{{ create_user }}"


- name: copy docker-compose.yml
  copy:
    src: files/docker-compose.yml
    dest: "/home/{{ create_user }}/compose/docker-compose.yml"
    owner: "{{ create_user }}"


- name: start containers
  community.docker.docker_compose:
    project_src: "/home/{{ create_user }}/compose/"
    state: present
  register: result

- name: print compose output
  ansible.builtin.debug:
    var: result
    verbosity: 2
