---
- name: "Configures Elsa - a Linux desktop"
  hosts: elsa
  user: igor
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - linux_common
    - linux_dev
    - linux_desktop
    - docker_host
