---
- name: "Configures Firefly - a home NAS/universal server"
  hosts: firefly
  user: igor
  become: true

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  vars:
    docker_data_root: /data/noshare/docker
    required_data_mounts:
      - /data/noshare
      - /data/other
      - /data/seriale
      - /data/filmy
      - /data/video2
      - /data/parity1

  roles:
    - linux_common
    - firefly
    - require_data_mounts
    - docker_host
    - minikube
    - jellyfin
    - snapraid
    - prometheus_server
