---
- name: "Configures Firefly - a home NAS/universal server"
  hosts: firefly
  user: igor
  become: true

  vars_files:
    - vars/main.yml

  roles:
    - linux_common
    - docker_host
    - firefly
    - jellyfin
    - snapraid
    - prometheus_server
