---
- name: "Configures Firefly - a home NAS/universal server"
  hosts: firefly
  user: igor
  become: true

  vars_files:
    - vars/main.yml
    - vars/vault.yml

  vars:
    docker_data_root: /data/noshare/docker

  roles:
    - linux_common
    - firefly
    - docker_host
    - minikube
    - jellyfin
    - snapraid
    - prometheus_server
