---
- name: Install packages
  ansible.builtin.apt:
    name: ['hd-idle', 'wsdd']
    state: latest

- name: Configure hd-idle
  ansible.builtin.lineinfile:
    path: /etc/default/hd-idle
    line: HD_IDLE_OPTS="-i 300 -l /var/log/hd-idle.log"
    state: present

- name: Configure WSDD
  ansible.builtin.lineinfile:
    path: /etc/default/wsdd
    line: WSDD_PARAMS="-n {{ samba_netbios_name }} -w {{ samba_workgroup }}"
    state: present

- name: Restart hd-idle
  ansible.builtin.service:
    name: hd-idle
    state: restarted
    enabled: true

- name: Restart syncthing
  ansible.builtin.service:
    name: syncthing@igor
    state: restarted
    enabled: true
