- name: Create a system user for samba
  loop: "{{ samba_users }}"
  ansible.builtin.user:
    name: "{{ item.name }}"
    state: present
    create_home: false
    shell: /bin/true
    password: '!'



- name: Create mount points for share directories
  loop: "{{ samba_shares }}"
  ansible.posix.mount:
    path: /data/{{ item.name }}
    src: LABEL={{ item.name }}
    fstype: ext4
    state: mounted
    opts: nodev,noexec,noatime,nofail,x-systemd.device-timeout=10


- name: Create mount points for non-share directories
  loop: "{{ no_shares }}"
  ansible.posix.mount:
    path: /data/{{ item.name }}
    src: LABEL={{ item.name }}
    fstype: ext4
    state: mounted
    opts: nodev,noexec,noatime,nofail,x-systemd.device-timeout=10




- name: Chown mount points for share directories
  loop: "{{ samba_shares }}"
  ansible.builtin.file:
    path: /data/{{ item.name }}
    state: directory
    owner: river
    recurse: true
  when: chown_shares is defined and chown_shares == true
