# File: roles/samba/tasks/main.yml
---

- name: Install Samba packages
  ansible.builtin.apt:
    name: "{{ samba_packages }}"
    state: latest
  tags: samba

- name: Install Samba VFS extensions packages
  ansible.builtin.apt:
    name: "{{ samba_vfs_packages }}"
    state: latest
  when: samba_vfs_packages is defined
  tags: samba

- name: Register Samba version
  ansible.builtin.shell: >
    set -o nounset -o pipefail -o errexit &&
    smbd --version | sed 's/Version //'
  args:
    executable: /bin/bash
  register: samba_version
  changed_when: false
  tags: samba

# - name: "Installed Samba version:"
#   debug:
#     msg: "{{ samba_version }}"
#   tags: samba

- name: Install SELinux package
  ansible.builtin.apt:
    name: "{{ samba_selinux_packages }}"
    state: latest
  when: ansible_selinux is defined and ansible_selinux.status == 'enabled'
  tags: samba

- name: Make sure SELinux boolean settings are correct
  ansible.posix.seboolean:
    name: "{{ item }}"
    state: true
    persistent: true
  with_items: "{{ samba_selinux_booleans }}"
  when: ansible_selinux is defined and ansible_selinux.status == 'enabled'
  tags: samba

- name: Create Samba shares root directory
  ansible.builtin.file:
    state: directory
    path: "{{ samba_shares_root }}"
    owner: root
    group: root
    mode: '0755'
  when: samba_shares|length > 0
  tags: samba

- name: Create share directories
  with_items: "{{ samba_shares }}"
  ansible.builtin.file:
    state: directory
    path: "{{ item.path | default([samba_shares_root, item.name] | join('/')) }}"
    owner: "{{ item.owner | default('root') }}"
    group: "{{ item.group | default('users') }}"
    mode: "{{ item.directory_mode | default('0775') }}"
    setype: "{{ item.setype | default('samba_share_t') }}"
  tags: samba

- name: Samba configuration
  ansible.builtin.template:
    dest: "{{ samba_configuration }}"
    mode: '0644'
    src: smb.conf.j2
    validate: 'testparm -s %s'
  notify:
    - Restart Samba services
  tags: samba

- name: Install global include file
  ansible.builtin.template:
    src: "{{ samba_global_include }}"
    dest: "{{ samba_configuration_dir }}"
    mode: '0644'
    validate: 'testparm -s %s'
  when: samba_global_include is defined
  notify:
    - Restart Samba services
  tags: samba

- name: Install home include file
  ansible.builtin.template:
    src: "{{ samba_homes_include }}"
    dest: "{{ samba_configuration_dir }}"
    mode: '0644'
    validate: 'testparm -s %s'
  when: samba_homes_include is defined
  notify:
    - Restart Samba services
  tags: samba

- name: Install share specific include files
  ansible.builtin.template:
    src: "{{ item.include_file }}"
    dest: "{{ samba_configuration_dir }}"
    mode: '0644'
    validate: 'testparm -s %s'
  when: item.include_file is defined
  notify:
    - Restart Samba services
  with_items: "{{ samba_shares }}"
  tags: samba

- name: Create username map file if needed
  ansible.builtin.template:
    dest: "{{ samba_username_map_file }}"
    mode: '0644'
    src: smbusers.j2
  notify:
    - Restart Samba services
  when: samba_username_map is defined
  tags: samba

- name: Start Samba service(s)
  ansible.builtin.service:
    name: "{{ item }}"
    state: started
    enabled: true
  with_items: "{{ samba_services }}"
  tags: samba

- name: Create Samba users if they don't exist yet
  ansible.builtin.shell: >
    set -o nounset -o pipefail -o errexit &&
    (pdbedit --user={{ item.name }} 2>&1 > /dev/null) \
    || (echo {{ item.password }}; echo {{ item.password }}) \
    | smbpasswd -s -a {{ item.name }}
  args:
    executable: /bin/bash
  with_items: "{{ samba_users }}"
  no_log: true
  register: create_user_output
  changed_when: "'Added user' in create_user_output.stdout"
  tags: samba
