---
- name: Install syncthing
  ansible.builtin.apt:
    name: ['syncthing']
    state: latest

- name: Create directory for synthing
  ansible.builtin.file:
    path: /data/noshare/syncthing
    state: directory
    owner: igor
    mode: '0700'

- name: Restart syncthing
  ansible.builtin.service:
    name: syncthing@igor
    state: restarted
    enabled: true
