#################################################
# DO Community Playbooks: Initial Server Setup
#################################################
---

- name: Add VS Code apt repository
  ansible.builtin.deb822_repository:
    name: vscode
    types: deb
    uris: https://packages.microsoft.com/repos/code
    suites: stable
    components: main
    signed_by: /etc/apt/trusted.gpg.d/microsoft.asc
    state: present
    install_python_debian: true

- name: Install dev packages
  ansible.builtin.apt:
    name: "{{ dev_packages }}"
    state: present
