---
- name: Install packages
  apt: 
    name: ['hd-idle', 'wsdd'] 
    state: present

- name: configure hd-idle
  ansible.builtin.lineinfile:
    path: /etc/default/hd-idle
    line: HD_IDLE_OPTS="-i 300 -l /var/log/hd-idle.log"
    state: present

- name: configure WSDD
  ansible.builtin.lineinfile:
    path: /etc/default/wsdd
    line: WSDD_PARAMS="-n {{ samba_netbios_name }} -w {{ samba_workgroup }}"
    state: present


- name: Restart hd-idle
  service:
    name: hd-idle
    state: restarted
    enabled: true

- name: Restart WSDD
  service:
    name: wsdd
    state: restarted
    enabled: true

- name: Generate backup script
  template:
    dest: /etc/cron.daily/rsync-backup.sh
    src: rsync-backup.sh.j2
